# Generated by Django 4.1.13 on 2024-03-27 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0001_initial"),
        ("lists", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="compilation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lists",
                to="lists.compilation",
            ),
        ),
        migrations.AlterField(
            model_name="listfilm",
            name="film",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="list_films",
                to="films.film",
            ),
        ),
    ]
