# Generated by Django 4.1.13 on 2024-04-01 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0004_alter_listfilm_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="compilation",
            name="maximum_list_length",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="rankingfilm",
            name="average_grade",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="rankingfilm",
            name="points_breakdown",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="rankingfilm",
            name="ranking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranking_films",
                to="lists.ranking",
            ),
        ),
    ]
