# Generated by Django 4.1.13 on 2024-03-26 22:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imdb_id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("tmdb_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=512)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "pt_br_title",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("release_date", models.DateField()),
                ("runtime", models.IntegerField(null=True)),
                ("synopsis", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imdb_id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("tmdb_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=512)),
                ("bio", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_death", models.DateField(blank=True, null=True)),
                (
                    "films",
                    models.ManyToManyField(
                        related_name="credited_people",
                        through="films.Credit",
                        to="films.film",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="credit",
            name="film",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credits",
                to="films.film",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credits",
                to="films.person",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="credit",
            unique_together={("person", "film", "role")},
        ),
    ]
