# Generated by Django 4.1.13 on 2024-03-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="role",
            field=models.CharField(
                choices=[
                    ("actor", "Actor"),
                    ("director", "Director"),
                    ("writer", "Writer"),
                ],
                max_length=100,
            ),
        ),
    ]
